import mongoose from "mongoose";
import dotenv from "dotenv";
import Book from "../models/Book";

dotenv.config();

const MONGODB_URI =
  process.env["MONGODB_URI"] ||
  "mongodb+srv://mickeym4044:e2ngduK5G9y8EWkJ@cluster0gcet.6sggum8.mongodb.net/gcet_db";

// Comprehensive Engineering Book Collection
const engineeringBooks = [
  // ==================== COMPUTER SCIENCE ENGINEERING ====================
  // Semester 1-2 (CSE)
  {
    title: "Introduction to Algorithms",
    author: "Thomas H. Cormen, Charles E. Leiserson",
    isbn: "9780262033848",
    department: "CSE",
    subBlock: "Algorithms & Data Structures",
    category: "academic",
    subject: "Algorithms",
    academicLevel: "undergraduate",
    semester: [1, 2, 3, 4],
    publisher: "MIT Press",
    publicationYear: 2009,
    edition: "3rd",
    pages: 1312,
    language: "English",
    description: "Comprehensive textbook on algorithms and data structures",
    totalCopies: 25,
    availableCopies: 20,
    location: "CSE Block A - Floor 2",
    shelfNumber: "CSE-ALG-001",
    status: "available",
    price: 1200,
    replacementCost: 1800,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["algorithms", "data structures", "complexity"],
  },
  {
    title: "Data Structures and Algorithms in Java",
    author: "Robert Lafore",
    isbn: "9780672324536",
    department: "CSE",
    subBlock: "Algorithms & Data Structures",
    category: "academic",
    subject: "Data Structures",
    academicLevel: "undergraduate",
    semester: [2, 3],
    publisher: "Sams Publishing",
    publicationYear: 2017,
    edition: "2nd",
    pages: 800,
    language: "English",
    description: "Practical approach to data structures and algorithms using Java",
    totalCopies: 20,
    availableCopies: 15,
    location: "CSE Block A - Floor 2",
    shelfNumber: "CSE-ALG-002",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["java", "data structures", "algorithms"],
  },
  {
    title: "Programming in C",
    author: "E. Balagurusamy",
    isbn: "9780070634534",
    department: "CSE",
    subBlock: "Programming Languages",
    category: "academic",
    subject: "C Programming",
    academicLevel: "undergraduate",
    semester: [1],
    publisher: "McGraw Hill",
    publicationYear: 2019,
    edition: "8th",
    pages: 549,
    language: "English",
    description: "Comprehensive guide to C programming language",
    totalCopies: 30,
    availableCopies: 25,
    location: "CSE Block A - Floor 1",
    shelfNumber: "CSE-PROG-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["c programming", "programming basics"],
  },
  {
    title: "Object-Oriented Programming with C++",
    author: "E. Balagurusamy",
    isbn: "9780070669086",
    department: "CSE",
    subBlock: "Programming Languages",
    category: "academic",
    subject: "C++ Programming",
    academicLevel: "undergraduate",
    semester: [2],
    publisher: "McGraw Hill",
    publicationYear: 2018,
    edition: "7th",
    pages: 568,
    language: "English",
    description: "Complete guide to object-oriented programming using C++",
    totalCopies: 28,
    availableCopies: 22,
    location: "CSE Block A - Floor 1",
    shelfNumber: "CSE-PROG-002",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["c++", "oop", "object-oriented"],
  },
  {
    title: "Python Programming",
    author: "John Zelle",
    isbn: "9781590282755",
    department: "CSE",
    subBlock: "Programming Languages",
    category: "academic",
    subject: "Python Programming",
    academicLevel: "undergraduate",
    semester: [1, 2],
    publisher: "Franklin Beedle",
    publicationYear: 2016,
    edition: "3rd",
    pages: 533,
    language: "English",
    description: "Introduction to computer science using Python",
    totalCopies: 25,
    availableCopies: 20,
    location: "CSE Block A - Floor 1",
    shelfNumber: "CSE-PROG-003",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["python", "programming", "scripting"],
  },
  {
    title: "Database System Concepts",
    author: "Abraham Silberschatz, Henry F. Korth",
    isbn: "9780073523323",
    department: "CSE",
    subBlock: "Database Systems",
    category: "academic",
    subject: "Database Management",
    academicLevel: "undergraduate",
    semester: [3, 4],
    publisher: "McGraw-Hill",
    publicationYear: 2019,
    edition: "7th",
    pages: 1376,
    language: "English",
    description: "Comprehensive coverage of database management systems",
    totalCopies: 30,
    availableCopies: 25,
    location: "CSE Block A - Floor 2",
    shelfNumber: "CSE-DB-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["database", "sql", "dbms"],
  },
  {
    title: "Database Management Systems",
    author: "Raghu Ramakrishnan, Johannes Gehrke",
    isbn: "9780072465631",
    department: "CSE",
    subBlock: "Database Systems",
    category: "academic",
    subject: "Database Management",
    academicLevel: "undergraduate",
    semester: [3, 4],
    publisher: "McGraw-Hill",
    publicationYear: 2014,
    edition: "3rd",
    pages: 1065,
    language: "English",
    description: "In-depth treatment of database management concepts",
    totalCopies: 25,
    availableCopies: 20,
    location: "CSE Block A - Floor 2",
    shelfNumber: "CSE-DB-002",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["database", "rdbms", "normalization"],
  },
  {
    title: "Operating System Concepts",
    author: "Abraham Silberschatz, Peter B. Galvin",
    isbn: "9781118063330",
    department: "CSE",
    subBlock: "Systems Programming",
    category: "academic",
    subject: "Operating Systems",
    academicLevel: "undergraduate",
    semester: [4, 5],
    publisher: "Wiley",
    publicationYear: 2018,
    edition: "10th",
    pages: 1040,
    language: "English",
    description: "Fundamental concepts of operating systems",
    totalCopies: 30,
    availableCopies: 24,
    location: "CSE Block A - Floor 3",
    shelfNumber: "CSE-OS-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["operating systems", "processes", "memory management"],
  },
  {
    title: "Modern Operating Systems",
    author: "Andrew S. Tanenbaum",
    isbn: "9780133591620",
    department: "CSE",
    subBlock: "Systems Programming",
    category: "academic",
    subject: "Operating Systems",
    academicLevel: "undergraduate",
    semester: [4, 5],
    publisher: "Pearson",
    publicationYear: 2014,
    edition: "4th",
    pages: 1136,
    language: "English",
    description: "Comprehensive guide to modern operating systems",
    totalCopies: 25,
    availableCopies: 20,
    location: "CSE Block A - Floor 3",
    shelfNumber: "CSE-OS-002",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["os", "unix", "linux", "windows"],
  },
  {
    title: "Computer Networks",
    author: "Andrew S. Tanenbaum, David J. Wetherall",
    isbn: "9780132126953",
    department: "CSE",
    subBlock: "Computer Networks",
    category: "academic",
    subject: "Computer Networks",
    academicLevel: "undergraduate",
    semester: [5, 6],
    publisher: "Pearson",
    publicationYear: 2010,
    edition: "5th",
    pages: 960,
    language: "English",
    description: "Comprehensive introduction to computer networking",
    totalCopies: 28,
    availableCopies: 22,
    location: "CSE Block A - Floor 3",
    shelfNumber: "CSE-NET-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["networks", "tcp/ip", "protocols"],
  },
  {
    title: "Data Communications and Networking",
    author: "Behrouz A. Forouzan",
    isbn: "9780073376226",
    department: "CSE",
    subBlock: "Computer Networks",
    category: "academic",
    subject: "Data Communications",
    academicLevel: "undergraduate",
    semester: [5, 6],
    publisher: "McGraw-Hill",
    publicationYear: 2012,
    edition: "5th",
    pages: 1264,
    language: "English",
    description: "Complete guide to data communications and networking",
    totalCopies: 25,
    availableCopies: 20,
    location: "CSE Block A - Floor 3",
    shelfNumber: "CSE-NET-002",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["networking", "data communication", "osi model"],
  },
  {
    title: "Computer Organization and Architecture",
    author: "William Stallings",
    isbn: "9780134101613",
    department: "CSE",
    subBlock: "Computer Architecture",
    category: "academic",
    subject: "Computer Architecture",
    academicLevel: "undergraduate",
    semester: [3, 4],
    publisher: "Pearson",
    publicationYear: 2015,
    edition: "10th",
    pages: 816,
    language: "English",
    description: "Comprehensive coverage of computer organization and architecture",
    totalCopies: 30,
    availableCopies: 25,
    location: "CSE Block A - Floor 2",
    shelfNumber: "CSE-ARCH-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["computer architecture", "assembly", "hardware"],
  },
  {
    title: "Computer Architecture: A Quantitative Approach",
    author: "John L. Hennessy, David A. Patterson",
    isbn: "9780128119051",
    department: "CSE",
    subBlock: "Computer Architecture",
    category: "academic",
    subject: "Computer Architecture",
    academicLevel: "undergraduate",
    semester: [4, 5],
    publisher: "Morgan Kaufmann",
    publicationYear: 2017,
    edition: "6th",
    pages: 936,
    language: "English",
    description: "Advanced topics in computer architecture",
    totalCopies: 20,
    availableCopies: 15,
    location: "CSE Block A - Floor 2",
    shelfNumber: "CSE-ARCH-002",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["architecture", "pipelining", "cache"],
  },
  {
    title: "Artificial Intelligence: A Modern Approach",
    author: "Stuart Russell, Peter Norvig",
    isbn: "9780136042594",
    department: "CSE",
    subBlock: "Artificial Intelligence",
    category: "academic",
    subject: "Artificial Intelligence",
    academicLevel: "undergraduate",
    semester: [6, 7],
    publisher: "Pearson",
    publicationYear: 2020,
    edition: "4th",
    pages: 1136,
    language: "English",
    description: "Comprehensive introduction to artificial intelligence",
    totalCopies: 30,
    availableCopies: 25,
    location: "CSE Block B - Floor 1",
    shelfNumber: "CSE-AI-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["ai", "machine learning", "neural networks"],
  },
  {
    title: "Machine Learning",
    author: "Tom M. Mitchell",
    isbn: "9780070428072",
    department: "CSE",
    subBlock: "Artificial Intelligence",
    category: "academic",
    subject: "Machine Learning",
    academicLevel: "undergraduate",
    semester: [6, 7],
    publisher: "McGraw-Hill",
    publicationYear: 1997,
    edition: "1st",
    pages: 414,
    language: "English",
    description: "Classic introduction to machine learning",
    totalCopies: 25,
    availableCopies: 20,
    location: "CSE Block B - Floor 1",
    shelfNumber: "CSE-AI-002",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["machine learning", "supervised learning", "neural networks"],
  },
  {
    title: "Deep Learning",
    author: "Ian Goodfellow, Yoshua Bengio",
    isbn: "9780262035613",
    department: "CSE",
    subBlock: "Artificial Intelligence",
    category: "academic",
    subject: "Deep Learning",
    academicLevel: "undergraduate",
    semester: [7, 8],
    publisher: "MIT Press",
    publicationYear: 2016,
    edition: "1st",
    pages: 800,
    language: "English",
    description: "Comprehensive textbook on deep learning",
    totalCopies: 22,
    availableCopies: 18,
    location: "CSE Block B - Floor 1",
    shelfNumber: "CSE-AI-003",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["deep learning", "neural networks", "cnn"],
  },
  {
    title: "Software Engineering",
    author: "Ian Sommerville",
    isbn: "9780133943030",
    department: "CSE",
    subBlock: "Software Engineering",
    category: "academic",
    subject: "Software Engineering",
    academicLevel: "undergraduate",
    semester: [5, 6],
    publisher: "Pearson",
    publicationYear: 2015,
    edition: "10th",
    pages: 816,
    language: "English",
    description: "Comprehensive guide to software engineering principles",
    totalCopies: 28,
    availableCopies: 23,
    location: "CSE Block B - Floor 2",
    shelfNumber: "CSE-SE-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["software engineering", "sdlc", "agile"],
  },
  {
    title: "Design Patterns: Elements of Reusable Object-Oriented Software",
    author: "Erich Gamma, Richard Helm",
    isbn: "9780201633610",
    department: "CSE",
    subBlock: "Software Engineering",
    category: "academic",
    subject: "Design Patterns",
    academicLevel: "undergraduate",
    semester: [6, 7],
    publisher: "Addison-Wesley",
    publicationYear: 1994,
    edition: "1st",
    pages: 416,
    language: "English",
    description: "Classic book on software design patterns",
    totalCopies: 20,
    availableCopies: 15,
    location: "CSE Block B - Floor 2",
    shelfNumber: "CSE-SE-002",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["design patterns", "oop", "software design"],
  },
  {
    title: "Compiler Design",
    author: "Alfred V. Aho, Monica S. Lam",
    isbn: "9780321486813",
    department: "CSE",
    subBlock: "Compiler Design",
    category: "academic",
    subject: "Compiler Design",
    academicLevel: "undergraduate",
    semester: [6, 7],
    publisher: "Pearson",
    publicationYear: 2006,
    edition: "2nd",
    pages: 1040,
    language: "English",
    description: "Comprehensive textbook on compiler construction",
    totalCopies: 22,
    availableCopies: 18,
    location: "CSE Block B - Floor 3",
    shelfNumber: "CSE-CD-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["compilers", "parsers", "lexical analysis"],
  },
  {
    title: "Theory of Computation",
    author: "Michael Sipser",
    isbn: "9781133187790",
    department: "CSE",
    subBlock: "Theory of Computation",
    category: "academic",
    subject: "Theory of Computation",
    academicLevel: "undergraduate",
    semester: [5, 6],
    publisher: "Cengage Learning",
    publicationYear: 2012,
    edition: "3rd",
    pages: 504,
    language: "English",
    description: "Introduction to the theory of computation",
    totalCopies: 25,
    availableCopies: 20,
    location: "CSE Block B - Floor 3",
    shelfNumber: "CSE-TOC-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["automata", "turing machines", "complexity theory"],
  },
  {
    title: "Computer Graphics: Principles and Practice",
    author: "John F. Hughes, Andries van Dam",
    isbn: "9780321399526",
    department: "CSE",
    subBlock: "Computer Graphics",
    category: "academic",
    subject: "Computer Graphics",
    academicLevel: "undergraduate",
    semester: [6, 7],
    publisher: "Addison-Wesley",
    publicationYear: 2013,
    edition: "3rd",
    pages: 1264,
    language: "English",
    description: "Comprehensive guide to computer graphics",
    totalCopies: 20,
    availableCopies: 16,
    location: "CSE Block B - Floor 2",
    shelfNumber: "CSE-CG-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["graphics", "opengl", "rendering"],
  },
  {
    title: "Cryptography and Network Security",
    author: "William Stallings",
    isbn: "9780134444284",
    department: "CSE",
    subBlock: "Cybersecurity",
    category: "academic",
    subject: "Cryptography",
    academicLevel: "undergraduate",
    semester: [7, 8],
    publisher: "Pearson",
    publicationYear: 2016,
    edition: "7th",
    pages: 768,
    language: "English",
    description: "Comprehensive coverage of cryptography and network security",
    totalCopies: 26,
    availableCopies: 21,
    location: "CSE Block B - Floor 3",
    shelfNumber: "CSE-SEC-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["cryptography", "security", "encryption"],
  },

  // ==================== ELECTRICAL ENGINEERING ====================
  {
    title: "Basic Electrical Engineering",
    author: "V. K. Mehta, Rohit Mehta",
    isbn: "9788121924405",
    department: "EEE",
    subBlock: "Fundamentals",
    category: "academic",
    subject: "Basic Electrical",
    academicLevel: "undergraduate",
    semester: [1, 2],
    publisher: "S. Chand Publishing",
    publicationYear: 2018,
    edition: "4th",
    pages: 624,
    language: "English",
    description: "Fundamentals of electrical engineering",
    totalCopies: 35,
    availableCopies: 30,
    location: "EEE Block A - Floor 1",
    shelfNumber: "EEE-FUND-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["basic electrical", "circuits", "fundamentals"],
  },
  {
    title: "Electrical Circuit Theory and Technology",
    author: "John Bird",
    isbn: "9780415662864",
    department: "EEE",
    subBlock: "Circuit Analysis",
    category: "academic",
    subject: "Circuit Analysis",
    academicLevel: "undergraduate",
    semester: [2, 3],
    publisher: "Routledge",
    publicationYear: 2017,
    edition: "6th",
    pages: 786,
    language: "English",
    description: "Comprehensive coverage of electrical circuit theory",
    totalCopies: 30,
    availableCopies: 25,
    location: "EEE Block A - Floor 1",
    shelfNumber: "EEE-CIRC-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["circuits", "ac analysis", "dc analysis"],
  },
  {
    title: "Network Analysis",
    author: "M. E. Van Valkenburg",
    isbn: "9788120301566",
    department: "EEE",
    subBlock: "Circuit Analysis",
    category: "academic",
    subject: "Network Analysis",
    academicLevel: "undergraduate",
    semester: [3, 4],
    publisher: "PHI Learning",
    publicationYear: 2015,
    edition: "3rd",
    pages: 568,
    language: "English",
    description: "Advanced network analysis techniques",
    totalCopies: 28,
    availableCopies: 23,
    location: "EEE Block A - Floor 1",
    shelfNumber: "EEE-CIRC-002",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["network analysis", "circuit theory", "mesh analysis"],
  },
  {
    title: "Electronic Devices and Circuit Theory",
    author: "Robert L. Boylestad, Louis Nashelsky",
    isbn: "9780132622264",
    department: "EEE",
    subBlock: "Electronics",
    category: "academic",
    subject: "Electronic Devices",
    academicLevel: "undergraduate",
    semester: [3, 4],
    publisher: "Pearson",
    publicationYear: 2012,
    edition: "11th",
    pages: 896,
    language: "English",
    description: "Comprehensive guide to electronic devices and circuits",
    totalCopies: 32,
    availableCopies: 27,
    location: "EEE Block A - Floor 2",
    shelfNumber: "EEE-ELEC-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["electronics", "semiconductors", "transistors"],
  },
  {
    title: "Digital Electronics",
    author: "R. P. Jain",
    isbn: "9780070669024",
    department: "EEE",
    subBlock: "Digital Electronics",
    category: "academic",
    subject: "Digital Electronics",
    academicLevel: "undergraduate",
    semester: [4, 5],
    publisher: "McGraw Hill",
    publicationYear: 2016,
    edition: "3rd",
    pages: 542,
    language: "English",
    description: "Fundamentals of digital electronics",
    totalCopies: 30,
    availableCopies: 25,
    location: "EEE Block A - Floor 2",
    shelfNumber: "EEE-DIGI-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["digital electronics", "logic gates", "flip-flops"],
  },
  {
    title: "Microprocessors and Microcontrollers",
    author: "Krishna Kant",
    isbn: "9788120336971",
    department: "EEE",
    subBlock: "Microprocessors",
    category: "academic",
    subject: "Microprocessors",
    academicLevel: "undergraduate",
    semester: [5, 6],
    publisher: "PHI Learning",
    publicationYear: 2010,
    edition: "1st",
    pages: 628,
    language: "English",
    description: "Introduction to microprocessors and microcontrollers",
    totalCopies: 28,
    availableCopies: 23,
    location: "EEE Block A - Floor 2",
    shelfNumber: "EEE-MICRO-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["microprocessors", "8085", "8086", "microcontrollers"],
  },
  {
    title: "Power System Analysis",
    author: "John J. Grainger, William D. Stevenson",
    isbn: "9780070612938",
    department: "EEE",
    subBlock: "Power Systems",
    category: "academic",
    subject: "Power Systems",
    academicLevel: "undergraduate",
    semester: [5, 6],
    publisher: "McGraw-Hill",
    publicationYear: 2016,
    edition: "4th",
    pages: 736,
    language: "English",
    description: "Comprehensive power system analysis",
    totalCopies: 30,
    availableCopies: 25,
    location: "EEE Block B - Floor 1",
    shelfNumber: "EEE-PWR-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["power systems", "load flow", "fault analysis"],
  },
  {
    title: "Electric Machinery Fundamentals",
    author: "Stephen J. Chapman",
    isbn: "9780073529547",
    department: "EEE",
    subBlock: "Electrical Machines",
    category: "academic",
    subject: "Electrical Machines",
    academicLevel: "undergraduate",
    semester: [4, 5],
    publisher: "McGraw-Hill",
    publicationYear: 2011,
    edition: "5th",
    pages: 752,
    language: "English",
    description: "Fundamentals of electrical machinery",
    totalCopies: 32,
    availableCopies: 27,
    location: "EEE Block B - Floor 1",
    shelfNumber: "EEE-MACH-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["electrical machines", "motors", "generators"],
  },
  {
    title: "Control Systems Engineering",
    author: "Norman S. Nise",
    isbn: "9781118170519",
    department: "EEE",
    subBlock: "Control Systems",
    category: "academic",
    subject: "Control Systems",
    academicLevel: "undergraduate",
    semester: [6, 7],
    publisher: "Wiley",
    publicationYear: 2015,
    edition: "7th",
    pages: 944,
    language: "English",
    description: "Comprehensive guide to control systems engineering",
    totalCopies: 28,
    availableCopies: 23,
    location: "EEE Block B - Floor 2",
    shelfNumber: "EEE-CTRL-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["control systems", "feedback", "pid controller"],
  },
  {
    title: "Signals and Systems",
    author: "Alan V. Oppenheim, Alan S. Willsky",
    isbn: "9780138147570",
    department: "EEE",
    subBlock: "Signal Processing",
    category: "academic",
    subject: "Signals and Systems",
    academicLevel: "undergraduate",
    semester: [4, 5],
    publisher: "Pearson",
    publicationYear: 1996,
    edition: "2nd",
    pages: 957,
    language: "English",
    description: "Classic textbook on signals and systems",
    totalCopies: 30,
    availableCopies: 25,
    location: "EEE Block B - Floor 2",
    shelfNumber: "EEE-SIG-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["signals", "systems", "fourier transform"],
  },
  {
    title: "Communication Systems",
    author: "Simon Haykin",
    isbn: "9780471697909",
    department: "EEE",
    subBlock: "Communication Systems",
    category: "academic",
    subject: "Communication Systems",
    academicLevel: "undergraduate",
    semester: [6, 7],
    publisher: "Wiley",
    publicationYear: 2008,
    edition: "5th",
    pages: 816,
    language: "English",
    description: "Comprehensive coverage of communication systems",
    totalCopies: 28,
    availableCopies: 23,
    location: "EEE Block B - Floor 3",
    shelfNumber: "EEE-COM-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["communication", "modulation", "analog communication"],
  },
  {
    title: "Electromagnetic Field Theory",
    author: "K. D. Prasad",
    isbn: "9788178086231",
    department: "EEE",
    subBlock: "Electromagnetics",
    category: "academic",
    subject: "Electromagnetic Theory",
    academicLevel: "undergraduate",
    semester: [3, 4],
    publisher: "Satya Prakashan",
    publicationYear: 2012,
    edition: "2nd",
    pages: 618,
    language: "English",
    description: "Fundamentals of electromagnetic field theory",
    totalCopies: 26,
    availableCopies: 21,
    location: "EEE Block A - Floor 3",
    shelfNumber: "EEE-EMF-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["electromagnetics", "maxwell equations", "waves"],
  },
  {
    title: "Power Electronics",
    author: "M. H. Rashid",
    isbn: "9780133125900",
    department: "EEE",
    subBlock: "Power Electronics",
    category: "academic",
    subject: "Power Electronics",
    academicLevel: "undergraduate",
    semester: [6, 7],
    publisher: "Pearson",
    publicationYear: 2013,
    edition: "4th",
    pages: 912,
    language: "English",
    description: "Comprehensive guide to power electronics",
    totalCopies: 30,
    availableCopies: 25,
    location: "EEE Block B - Floor 3",
    shelfNumber: "EEE-PE-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["power electronics", "converters", "inverters"],
  },

  // ==================== MECHANICAL ENGINEERING ====================
  {
    title: "Engineering Mechanics: Statics",
    author: "J. L. Meriam, L. G. Kraige",
    isbn: "9781118807330",
    department: "MECH",
    subBlock: "Engineering Mechanics",
    category: "academic",
    subject: "Statics",
    academicLevel: "undergraduate",
    semester: [1, 2],
    publisher: "Wiley",
    publicationYear: 2014,
    edition: "8th",
    pages: 680,
    language: "English",
    description: "Fundamentals of engineering mechanics - statics",
    totalCopies: 35,
    availableCopies: 30,
    location: "MECH Block A - Floor 1",
    shelfNumber: "MECH-MECH-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["statics", "equilibrium", "forces"],
  },
  {
    title: "Engineering Mechanics: Dynamics",
    author: "J. L. Meriam, L. G. Kraige",
    isbn: "9781118885840",
    department: "MECH",
    subBlock: "Engineering Mechanics",
    category: "academic",
    subject: "Dynamics",
    academicLevel: "undergraduate",
    semester: [2, 3],
    publisher: "Wiley",
    publicationYear: 2015,
    edition: "8th",
    pages: 736,
    language: "English",
    description: "Fundamentals of engineering mechanics - dynamics",
    totalCopies: 35,
    availableCopies: 30,
    location: "MECH Block A - Floor 1",
    shelfNumber: "MECH-MECH-002",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["dynamics", "kinematics", "kinetics"],
  },
  {
    title: "Strength of Materials",
    author: "R. K. Bansal",
    isbn: "9788131808054",
    department: "MECH",
    subBlock: "Solid Mechanics",
    category: "academic",
    subject: "Strength of Materials",
    academicLevel: "undergraduate",
    semester: [3, 4],
    publisher: "Laxmi Publications",
    publicationYear: 2012,
    edition: "5th",
    pages: 748,
    language: "English",
    description: "Comprehensive guide to strength of materials",
    totalCopies: 32,
    availableCopies: 27,
    location: "MECH Block A - Floor 2",
    shelfNumber: "MECH-SOM-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["strength of materials", "stress", "strain"],
  },
  {
    title: "Mechanics of Materials",
    author: "Ferdinand P. Beer, E. Russell Johnston Jr.",
    isbn: "9780073398235",
    department: "MECH",
    subBlock: "Solid Mechanics",
    category: "academic",
    subject: "Mechanics of Materials",
    academicLevel: "undergraduate",
    semester: [3, 4],
    publisher: "McGraw-Hill",
    publicationYear: 2014,
    edition: "7th",
    pages: 816,
    language: "English",
    description: "In-depth coverage of mechanics of materials",
    totalCopies: 30,
    availableCopies: 25,
    location: "MECH Block A - Floor 2",
    shelfNumber: "MECH-SOM-002",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["mechanics", "material properties", "deformation"],
  },
  {
    title: "Thermodynamics: An Engineering Approach",
    author: "Yunus A. Cengel, Michael A. Boles",
    isbn: "9780073398174",
    department: "MECH",
    subBlock: "Thermal Engineering",
    category: "academic",
    subject: "Thermodynamics",
    academicLevel: "undergraduate",
    semester: [3, 4],
    publisher: "McGraw-Hill",
    publicationYear: 2014,
    edition: "8th",
    pages: 1024,
    language: "English",
    description: "Comprehensive textbook on thermodynamics",
    totalCopies: 35,
    availableCopies: 30,
    location: "MECH Block A - Floor 3",
    shelfNumber: "MECH-THERM-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["thermodynamics", "heat transfer", "energy"],
  },
  {
    title: "Fluid Mechanics",
    author: "Frank M. White",
    isbn: "9780073398273",
    department: "MECH",
    subBlock: "Fluid Mechanics",
    category: "academic",
    subject: "Fluid Mechanics",
    academicLevel: "undergraduate",
    semester: [4, 5],
    publisher: "McGraw-Hill",
    publicationYear: 2015,
    edition: "8th",
    pages: 864,
    language: "English",
    description: "Comprehensive guide to fluid mechanics",
    totalCopies: 32,
    availableCopies: 27,
    location: "MECH Block B - Floor 1",
    shelfNumber: "MECH-FLUID-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["fluid mechanics", "flow", "hydraulics"],
  },
  {
    title: "Heat and Mass Transfer",
    author: "Yunus A. Cengel",
    isbn: "9780073398181",
    department: "MECH",
    subBlock: "Thermal Engineering",
    category: "academic",
    subject: "Heat Transfer",
    academicLevel: "undergraduate",
    semester: [5, 6],
    publisher: "McGraw-Hill",
    publicationYear: 2014,
    edition: "5th",
    pages: 992,
    language: "English",
    description: "Comprehensive coverage of heat and mass transfer",
    totalCopies: 30,
    availableCopies: 25,
    location: "MECH Block A - Floor 3",
    shelfNumber: "MECH-THERM-002",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["heat transfer", "conduction", "convection"],
  },
  {
    title: "Machine Design",
    author: "R. S. Khurmi, J. K. Gupta",
    isbn: "9788121925372",
    department: "MECH",
    subBlock: "Machine Design",
    category: "academic",
    subject: "Machine Design",
    academicLevel: "undergraduate",
    semester: [5, 6],
    publisher: "S. Chand Publishing",
    publicationYear: 2015,
    edition: "14th",
    pages: 1264,
    language: "English",
    description: "Complete guide to machine design",
    totalCopies: 32,
    availableCopies: 27,
    location: "MECH Block B - Floor 2",
    shelfNumber: "MECH-DESIGN-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["machine design", "gears", "bearings"],
  },
  {
    title: "Theory of Machines",
    author: "S. S. Rattan",
    isbn: "9780070681880",
    department: "MECH",
    subBlock: "Theory of Machines",
    category: "academic",
    subject: "Theory of Machines",
    academicLevel: "undergraduate",
    semester: [4, 5],
    publisher: "McGraw Hill",
    publicationYear: 2014,
    edition: "4th",
    pages: 752,
    language: "English",
    description: "Fundamentals of theory of machines",
    totalCopies: 30,
    availableCopies: 25,
    location: "MECH Block B - Floor 2",
    shelfNumber: "MECH-TOM-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["mechanisms", "kinematics", "dynamics of machines"],
  },
  {
    title: "Manufacturing Technology",
    author: "P. N. Rao",
    isbn: "9780070648548",
    department: "MECH",
    subBlock: "Manufacturing",
    category: "academic",
    subject: "Manufacturing Processes",
    academicLevel: "undergraduate",
    semester: [5, 6],
    publisher: "McGraw Hill",
    publicationYear: 2017,
    edition: "3rd",
    pages: 624,
    language: "English",
    description: "Comprehensive coverage of manufacturing technology",
    totalCopies: 30,
    availableCopies: 25,
    location: "MECH Block B - Floor 3",
    shelfNumber: "MECH-MFG-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["manufacturing", "machining", "casting"],
  },
  {
    title: "Industrial Engineering and Management",
    author: "O. P. Khanna",
    isbn: "9788192496283",
    department: "MECH",
    subBlock: "Industrial Engineering",
    category: "academic",
    subject: "Industrial Engineering",
    academicLevel: "undergraduate",
    semester: [7, 8],
    publisher: "Dhanpat Rai Publications",
    publicationYear: 2015,
    edition: "17th",
    pages: 1048,
    language: "English",
    description: "Complete guide to industrial engineering and management",
    totalCopies: 25,
    availableCopies: 20,
    location: "MECH Block C - Floor 1",
    shelfNumber: "MECH-IE-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["industrial engineering", "production planning", "quality control"],
  },
  {
    title: "Automobile Engineering",
    author: "Kirpal Singh",
    isbn: "9788131803370",
    department: "MECH",
    subBlock: "Automobile Engineering",
    category: "academic",
    subject: "Automobile Engineering",
    academicLevel: "undergraduate",
    semester: [7, 8],
    publisher: "Standard Publishers",
    publicationYear: 2011,
    edition: "13th",
    pages: 1128,
    language: "English",
    description: "Comprehensive textbook on automobile engineering",
    totalCopies: 28,
    availableCopies: 23,
    location: "MECH Block C - Floor 2",
    shelfNumber: "MECH-AUTO-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["automobile", "engines", "transmission"],
  },
  {
    title: "Refrigeration and Air Conditioning",
    author: "C. P. Arora",
    isbn: "9780070491656",
    department: "MECH",
    subBlock: "Thermal Engineering",
    category: "academic",
    subject: "Refrigeration and AC",
    academicLevel: "undergraduate",
    semester: [6, 7],
    publisher: "McGraw Hill",
    publicationYear: 2009,
    edition: "3rd",
    pages: 744,
    language: "English",
    description: "Complete coverage of refrigeration and air conditioning",
    totalCopies: 26,
    availableCopies: 21,
    location: "MECH Block A - Floor 3",
    shelfNumber: "MECH-THERM-003",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["refrigeration", "air conditioning", "hvac"],
  },

  // ==================== CIVIL ENGINEERING ====================
  {
    title: "Engineering Mechanics",
    author: "S. S. Bhavikatti",
    isbn: "9788122416572",
    department: "CIVIL",
    subBlock: "Engineering Mechanics",
    category: "academic",
    subject: "Engineering Mechanics",
    academicLevel: "undergraduate",
    semester: [1, 2],
    publisher: "New Age International",
    publicationYear: 2015,
    edition: "2nd",
    pages: 492,
    language: "English",
    description: "Fundamentals of engineering mechanics for civil engineers",
    totalCopies: 35,
    availableCopies: 30,
    location: "CIVIL Block A - Floor 1",
    shelfNumber: "CIVIL-MECH-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["mechanics", "statics", "dynamics"],
  },
  {
    title: "Surveying and Levelling",
    author: "N. N. Basak",
    isbn: "9789386173171",
    department: "CIVIL",
    subBlock: "Surveying",
    category: "academic",
    subject: "Surveying",
    academicLevel: "undergraduate",
    semester: [2, 3],
    publisher: "McGraw Hill",
    publicationYear: 2017,
    edition: "3rd",
    pages: 632,
    language: "English",
    description: "Complete guide to surveying and levelling",
    totalCopies: 30,
    availableCopies: 25,
    location: "CIVIL Block A - Floor 1",
    shelfNumber: "CIVIL-SURV-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["surveying", "levelling", "theodolite"],
  },
  {
    title: "Strength of Materials",
    author: "S. S. Rattan",
    isbn: "9780070145986",
    department: "CIVIL",
    subBlock: "Structural Analysis",
    category: "academic",
    subject: "Strength of Materials",
    academicLevel: "undergraduate",
    semester: [3, 4],
    publisher: "McGraw Hill",
    publicationYear: 2011,
    edition: "2nd",
    pages: 824,
    language: "English",
    description: "Comprehensive coverage of strength of materials",
    totalCopies: 32,
    availableCopies: 27,
    location: "CIVIL Block A - Floor 2",
    shelfNumber: "CIVIL-SOM-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["strength of materials", "stress", "strain"],
  },
  {
    title: "Structural Analysis",
    author: "R. C. Hibbeler",
    isbn: "9780133942842",
    department: "CIVIL",
    subBlock: "Structural Analysis",
    category: "academic",
    subject: "Structural Analysis",
    academicLevel: "undergraduate",
    semester: [4, 5],
    publisher: "Pearson",
    publicationYear: 2014,
    edition: "9th",
    pages: 736,
    language: "English",
    description: "Fundamentals of structural analysis",
    totalCopies: 30,
    availableCopies: 25,
    location: "CIVIL Block A - Floor 2",
    shelfNumber: "CIVIL-STRUCT-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["structural analysis", "beams", "frames"],
  },
  {
    title: "Reinforced Concrete Design",
    author: "S. N. Sinha",
    isbn: "9780070648395",
    department: "CIVIL",
    subBlock: "Concrete Technology",
    category: "academic",
    subject: "RCC Design",
    academicLevel: "undergraduate",
    semester: [5, 6],
    publisher: "McGraw Hill",
    publicationYear: 2013,
    edition: "3rd",
    pages: 672,
    language: "English",
    description: "Complete guide to reinforced concrete design",
    totalCopies: 32,
    availableCopies: 27,
    location: "CIVIL Block A - Floor 3",
    shelfNumber: "CIVIL-RCC-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["rcc design", "concrete", "reinforcement"],
  },
  {
    title: "Steel Structures Design and Behaviour",
    author: "Charles G. Salmon, John E. Johnson",
    isbn: "9780060464639",
    department: "CIVIL",
    subBlock: "Steel Structures",
    category: "academic",
    subject: "Steel Design",
    academicLevel: "undergraduate",
    semester: [6, 7],
    publisher: "Pearson",
    publicationYear: 2008,
    edition: "5th",
    pages: 888,
    language: "English",
    description: "Comprehensive guide to steel structure design",
    totalCopies: 28,
    availableCopies: 23,
    location: "CIVIL Block B - Floor 1",
    shelfNumber: "CIVIL-STEEL-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["steel structures", "design", "connections"],
  },
  {
    title: "Soil Mechanics and Foundation Engineering",
    author: "K. R. Arora",
    isbn: "9788121908542",
    department: "CIVIL",
    subBlock: "Geotechnical Engineering",
    category: "academic",
    subject: "Soil Mechanics",
    academicLevel: "undergraduate",
    semester: [4, 5],
    publisher: "Standard Publishers",
    publicationYear: 2017,
    edition: "8th",
    pages: 1064,
    language: "English",
    description: "Complete textbook on soil mechanics and foundations",
    totalCopies: 32,
    availableCopies: 27,
    location: "CIVIL Block B - Floor 2",
    shelfNumber: "CIVIL-SOIL-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["soil mechanics", "foundations", "geotechnical"],
  },
  {
    title: "Transportation Engineering",
    author: "S. K. Khanna, C. E. G. Justo",
    isbn: "9788184893984",
    department: "CIVIL",
    subBlock: "Transportation Engineering",
    category: "academic",
    subject: "Transportation Engineering",
    academicLevel: "undergraduate",
    semester: [6, 7],
    publisher: "Nem Chand & Bros",
    publicationYear: 2013,
    edition: "10th",
    pages: 1112,
    language: "English",
    description: "Comprehensive coverage of transportation engineering",
    totalCopies: 28,
    availableCopies: 23,
    location: "CIVIL Block B - Floor 3",
    shelfNumber: "CIVIL-TRANS-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["transportation", "highways", "traffic"],
  },
  {
    title: "Environmental Engineering",
    author: "H. S. Peavy, D. R. Rowe, G. Tchobanoglous",
    isbn: "9780070494947",
    department: "CIVIL",
    subBlock: "Environmental Engineering",
    category: "academic",
    subject: "Environmental Engineering",
    academicLevel: "undergraduate",
    semester: [5, 6],
    publisher: "McGraw Hill",
    publicationYear: 1985,
    edition: "1st",
    pages: 736,
    language: "English",
    description: "Fundamentals of environmental engineering",
    totalCopies: 26,
    availableCopies: 21,
    location: "CIVIL Block C - Floor 1",
    shelfNumber: "CIVIL-ENV-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["environmental", "water supply", "wastewater"],
  },
  {
    title: "Fluid Mechanics and Hydraulic Machines",
    author: "R. K. Bansal",
    isbn: "9788131808047",
    department: "CIVIL",
    subBlock: "Hydraulic Engineering",
    category: "academic",
    subject: "Fluid Mechanics",
    academicLevel: "undergraduate",
    semester: [3, 4],
    publisher: "Laxmi Publications",
    publicationYear: 2012,
    edition: "9th",
    pages: 1056,
    language: "English",
    description: "Complete guide to fluid mechanics and hydraulic machines",
    totalCopies: 30,
    availableCopies: 25,
    location: "CIVIL Block C - Floor 2",
    shelfNumber: "CIVIL-FLUID-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["fluid mechanics", "hydraulics", "pumps"],
  },
  {
    title: "Construction Planning and Management",
    author: "P. S. Gahlot, P. M. Dhir",
    isbn: "9788122415896",
    department: "CIVIL",
    subBlock: "Construction Management",
    category: "academic",
    subject: "Construction Management",
    academicLevel: "undergraduate",
    semester: [7, 8],
    publisher: "New Age International",
    publicationYear: 2010,
    edition: "3rd",
    pages: 592,
    language: "English",
    description: "Comprehensive guide to construction planning and management",
    totalCopies: 25,
    availableCopies: 20,
    location: "CIVIL Block C - Floor 3",
    shelfNumber: "CIVIL-CONST-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["construction management", "planning", "scheduling"],
  },

  // ==================== ELECTRONICS & COMMUNICATION ENGINEERING ====================
  {
    title: "Electronic Devices and Circuits",
    author: "J. B. Gupta",
    isbn: "9788121923279",
    department: "ECE",
    subBlock: "Electronics Fundamentals",
    category: "academic",
    subject: "Electronic Devices",
    academicLevel: "undergraduate",
    semester: [2, 3],
    publisher: "S K Kataria & Sons",
    publicationYear: 2014,
    edition: "2nd",
    pages: 724,
    language: "English",
    description: "Complete coverage of electronic devices and circuits",
    totalCopies: 30,
    availableCopies: 25,
    location: "ECE Block A - Floor 1",
    shelfNumber: "ECE-DEV-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["electronics", "diodes", "transistors"],
  },
  {
    title: "Digital Signal Processing",
    author: "John G. Proakis, Dimitris G. Manolakis",
    isbn: "9780131873742",
    department: "ECE",
    subBlock: "Signal Processing",
    category: "academic",
    subject: "Digital Signal Processing",
    academicLevel: "undergraduate",
    semester: [5, 6],
    publisher: "Pearson",
    publicationYear: 2006,
    edition: "4th",
    pages: 1104,
    language: "English",
    description: "Comprehensive textbook on digital signal processing",
    totalCopies: 28,
    availableCopies: 23,
    location: "ECE Block A - Floor 2",
    shelfNumber: "ECE-DSP-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["dsp", "filters", "fft"],
  },
  {
    title: "Analog Communication Systems",
    author: "Wayne Tomasi",
    isbn: "9780130408792",
    department: "ECE",
    subBlock: "Communication Systems",
    category: "academic",
    subject: "Analog Communication",
    academicLevel: "undergraduate",
    semester: [5, 6],
    publisher: "Pearson",
    publicationYear: 2003,
    edition: "5th",
    pages: 528,
    language: "English",
    description: "Complete guide to analog communication systems",
    totalCopies: 26,
    availableCopies: 21,
    location: "ECE Block A - Floor 3",
    shelfNumber: "ECE-COM-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["analog communication", "am", "fm"],
  },
  {
    title: "Digital Communication",
    author: "Simon Haykin",
    isbn: "9780471625490",
    department: "ECE",
    subBlock: "Communication Systems",
    category: "academic",
    subject: "Digital Communication",
    academicLevel: "undergraduate",
    semester: [6, 7],
    publisher: "Wiley",
    publicationYear: 2000,
    edition: "1st",
    pages: 816,
    language: "English",
    description: "Fundamentals of digital communication",
    totalCopies: 28,
    availableCopies: 23,
    location: "ECE Block A - Floor 3",
    shelfNumber: "ECE-COM-002",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["digital communication", "modulation", "coding"],
  },
  {
    title: "VLSI Design",
    author: "Debaprasad Das",
    isbn: "9780198089810",
    department: "ECE",
    subBlock: "VLSI & Embedded Systems",
    category: "academic",
    subject: "VLSI Design",
    academicLevel: "undergraduate",
    semester: [7, 8],
    publisher: "Oxford University Press",
    publicationYear: 2010,
    edition: "1st",
    pages: 704,
    language: "English",
    description: "Comprehensive guide to VLSI design",
    totalCopies: 25,
    availableCopies: 20,
    location: "ECE Block B - Floor 1",
    shelfNumber: "ECE-VLSI-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["vlsi", "cmos", "ic design"],
  },
  {
    title: "Microwave Engineering",
    author: "David M. Pozar",
    isbn: "9780470631553",
    department: "ECE",
    subBlock: "Microwave Engineering",
    category: "academic",
    subject: "Microwave Engineering",
    academicLevel: "undergraduate",
    semester: [7, 8],
    publisher: "Wiley",
    publicationYear: 2011,
    edition: "4th",
    pages: 752,
    language: "English",
    description: "Complete coverage of microwave engineering",
    totalCopies: 22,
    availableCopies: 18,
    location: "ECE Block B - Floor 2",
    shelfNumber: "ECE-MW-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["microwave", "antennas", "waveguides"],
  },
  {
    title: "Embedded Systems",
    author: "Rajkamal",
    isbn: "9780070648241",
    department: "ECE",
    subBlock: "VLSI & Embedded Systems",
    category: "academic",
    subject: "Embedded Systems",
    academicLevel: "undergraduate",
    semester: [6, 7],
    publisher: "McGraw Hill",
    publicationYear: 2015,
    edition: "3rd",
    pages: 680,
    language: "English",
    description: "Comprehensive guide to embedded systems",
    totalCopies: 28,
    availableCopies: 23,
    location: "ECE Block B - Floor 1",
    shelfNumber: "ECE-EMB-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["embedded systems", "microcontrollers", "rtos"],
  },
  {
    title: "Wireless Communication and Networks",
    author: "William Stallings",
    isbn: "9780131918351",
    department: "ECE",
    subBlock: "Wireless Communication",
    category: "academic",
    subject: "Wireless Networks",
    academicLevel: "undergraduate",
    semester: [7, 8],
    publisher: "Pearson",
    publicationYear: 2004,
    edition: "2nd",
    pages: 624,
    language: "English",
    description: "Complete guide to wireless communication and networks",
    totalCopies: 26,
    availableCopies: 21,
    location: "ECE Block B - Floor 3",
    shelfNumber: "ECE-WL-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["wireless", "cellular", "wifi"],
  },
  {
    title: "Optical Fiber Communications",
    author: "Gerd Keiser",
    isbn: "9780070634398",
    department: "ECE",
    subBlock: "Optical Communication",
    category: "academic",
    subject: "Optical Communication",
    academicLevel: "undergraduate",
    semester: [7, 8],
    publisher: "McGraw Hill",
    publicationYear: 2010,
    edition: "4th",
    pages: 528,
    language: "English",
    description: "Fundamentals of optical fiber communications",
    totalCopies: 24,
    availableCopies: 19,
    location: "ECE Block B - Floor 3",
    shelfNumber: "ECE-OPT-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["optical communication", "fiber optics", "laser"],
  },

  // ==================== ADDITIONAL BOOKS (Continue to reach 1000+) ====================
  // Adding more books for Mathematics, Physics, Chemistry, and other common subjects

  {
    title: "Higher Engineering Mathematics",
    author: "B. S. Grewal",
    isbn: "9788193241585",
    department: "GENERAL",
    subBlock: "Mathematics",
    category: "academic",
    subject: "Engineering Mathematics",
    academicLevel: "undergraduate",
    semester: [1, 2, 3, 4],
    publisher: "Khanna Publishers",
    publicationYear: 2018,
    edition: "44th",
    pages: 1344,
    language: "English",
    description: "Comprehensive engineering mathematics textbook",
    totalCopies: 50,
    availableCopies: 45,
    location: "General Block - Floor 1",
    shelfNumber: "MATH-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["mathematics", "calculus", "differential equations"],
  },
  {
    title: "Advanced Engineering Mathematics",
    author: "Erwin Kreyszig",
    isbn: "9780470458365",
    department: "GENERAL",
    subBlock: "Mathematics",
    category: "academic",
    subject: "Advanced Mathematics",
    academicLevel: "undergraduate",
    semester: [3, 4, 5],
    publisher: "Wiley",
    publicationYear: 2011,
    edition: "10th",
    pages: 1264,
    language: "English",
    description: "Advanced topics in engineering mathematics",
    totalCopies: 40,
    availableCopies: 35,
    location: "General Block - Floor 1",
    shelfNumber: "MATH-002",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["mathematics", "linear algebra", "fourier series"],
  },
  {
    title: "Engineering Physics",
    author: "S. K. Gupta",
    isbn: "9789350142042",
    department: "GENERAL",
    subBlock: "Physics",
    category: "academic",
    subject: "Engineering Physics",
    academicLevel: "undergraduate",
    semester: [1, 2],
    publisher: "Krishna Prakashan Media",
    publicationYear: 2012,
    edition: "2nd",
    pages: 824,
    language: "English",
    description: "Fundamentals of engineering physics",
    totalCopies: 45,
    availableCopies: 40,
    location: "General Block - Floor 2",
    shelfNumber: "PHY-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["physics", "quantum mechanics", "waves"],
  },
  {
    title: "Engineering Chemistry",
    author: "Jain & Jain",
    isbn: "9788121903653",
    department: "GENERAL",
    subBlock: "Chemistry",
    category: "academic",
    subject: "Engineering Chemistry",
    academicLevel: "undergraduate",
    semester: [1, 2],
    publisher: "Dhanpat Rai Publishing",
    publicationYear: 2014,
    edition: "16th",
    pages: 652,
    language: "English",
    description: "Comprehensive engineering chemistry textbook",
    totalCopies: 45,
    availableCopies: 40,
    location: "General Block - Floor 2",
    shelfNumber: "CHEM-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["chemistry", "electrochemistry", "polymers"],
  },
  {
    title: "Technical Communication",
    author: "Meenakshi Raman, Sangeeta Sharma",
    isbn: "9780198099987",
    department: "GENERAL",
    subBlock: "Communication Skills",
    category: "academic",
    subject: "Communication Skills",
    academicLevel: "undergraduate",
    semester: [1, 2],
    publisher: "Oxford University Press",
    publicationYear: 2015,
    edition: "2nd",
    pages: 424,
    language: "English",
    description: "Guide to technical communication for engineers",
    totalCopies: 35,
    availableCopies: 30,
    location: "General Block - Floor 3",
    shelfNumber: "COMM-001",
    status: "available",
    price: 800,
    replacementCost: 1200,
    dailyFine: 5,
    maxBorrowDays: 14,
    addedBy: "system",
    tags: ["communication", "writing", "presentation"],
  },
];

// Function to generate additional books to reach 1000+
function generateAdditionalBooks(): any[] {
  const additionalBooks = [];
  const departments = ["CSE", "EEE", "MECH", "CIVIL", "ECE"];
  const categories = ["academic", "reference"];
  const subjectSuffixes = [
    "Part I",
    "Part II",
    "Advanced Topics",
    "Practical Guide",
    "Problem Solving",
    "Lab Manual",
    "Workbook",
    "Reference Manual",
    "Case Studies",
    "Projects",
  ];

  const subBlocks = {
    CSE: [
      "Algorithms & Data Structures",
      "Programming Languages",
      "Database Systems",
      "Systems Programming",
      "Computer Networks",
      "Artificial Intelligence",
      "Software Engineering",
    ],
    EEE: [
      "Circuit Analysis",
      "Electronics",
      "Power Systems",
      "Control Systems",
      "Signal Processing",
      "Communication Systems",
    ],
    MECH: [
      "Thermal Engineering",
      "Solid Mechanics",
      "Fluid Mechanics",
      "Machine Design",
      "Manufacturing",
    ],
    CIVIL: [
      "Structural Analysis",
      "Geotechnical Engineering",
      "Transportation Engineering",
      "Environmental Engineering",
    ],
    ECE: [
      "Signal Processing",
      "Communication Systems",
      "VLSI & Embedded Systems",
      "Microwave Engineering",
    ],
  };

  // Generate books to reach 1000+
  for (let i = 0; i < 950; i++) {
    const dept = departments[i % departments.length] as keyof typeof subBlocks;
    const subBlockArray = subBlocks[dept];
    const subBlock = subBlockArray[i % subBlockArray.length] || "General Engineering";
    const suffix = subjectSuffixes[i % subjectSuffixes.length];
    const semester = [(i % 8) + 1];

    additionalBooks.push({
      title: `${subBlock} ${suffix} Vol. ${Math.floor(i / 10) + 1}`,
      author: `Dr. ${String.fromCharCode(65 + (i % 26))}. ${String.fromCharCode(65 + ((i + 1) % 26))}. Kumar`,
      isbn: `978${String(1000000000 + i).substring(1)}`,
      department: dept,
      subBlock: subBlock,
      category: categories[i % 2] as "academic" | "reference",
      subject: subBlock,
      academicLevel: "undergraduate",
      semester: semester,
      publisher: ["McGraw Hill", "Pearson", "Wiley", "PHI Learning"][i % 4],
      publicationYear: 2010 + (i % 13),
      edition: `${(i % 5) + 1}th`,
      pages: 400 + (i % 600),
      language: "English",
      description: `Advanced textbook on ${subBlock}`,
      totalCopies: 15 + (i % 15),
      availableCopies: 10 + (i % 10),
      location: `${dept} Block ${String.fromCharCode(65 + (i % 3))} - Floor ${(i % 3) + 1}`,
      shelfNumber: `${dept}-${String.fromCharCode(65 + (i % 26))}-${String(i + 1).padStart(3, "0")}`,
      status: "available",
      price: 500 + (i % 1000),
      replacementCost: 750 + (i % 1500),
      dailyFine: 5,
      maxBorrowDays: 14,
      addedBy: "system",
      tags: [subBlock.toLowerCase(), "engineering", dept.toLowerCase()],
    });
  }

  return additionalBooks;
}

async function seedEngineeringBooks() {
  try {
    console.log("🔗 Connecting to MongoDB...");
    await mongoose.connect(MONGODB_URI);
    console.log("✅ Connected to MongoDB successfully!");

    console.log("\n🗑️  Clearing existing books...");
    await Book.deleteMany({});
    console.log("✅ Existing books cleared!");

    // Combine featured books with generated books
    const allBooks = [...engineeringBooks, ...generateAdditionalBooks()];

    console.log(`\n📚 Seeding ${allBooks.length} engineering books...`);

    // Insert books in batches for better performance
    const batchSize = 100;
    let inserted = 0;

    for (let i = 0; i < allBooks.length; i += batchSize) {
      const batch = allBooks.slice(i, i + batchSize);
      await Book.insertMany(batch);
      inserted += batch.length;
      console.log(`   ✓ Inserted ${inserted}/${allBooks.length} books`);
    }

    console.log("\n" + "=".repeat(70));
    console.log("🎉 BOOKS SEEDED SUCCESSFULLY!");
    console.log("=".repeat(70));

    // Statistics
    const stats = await Book.aggregate([
      {
        $group: {
          _id: "$department",
          totalBooks: { $sum: 1 },
          totalCopies: { $sum: "$totalCopies" },
          availableCopies: { $sum: "$availableCopies" },
        },
      },
      { $sort: { _id: 1 } },
    ]);

    console.log("\n📊 DEPARTMENT-WISE STATISTICS:");
    console.log("-".repeat(70));
    stats.forEach((stat) => {
      console.log(
        `   ${stat._id.padEnd(10)} | Books: ${String(stat.totalBooks).padStart(4)} | ` +
          `Total Copies: ${String(stat.totalCopies).padStart(4)} | ` +
          `Available: ${String(stat.availableCopies).padStart(4)}`
      );
    });

    console.log("\n✅ Total Books in Database:", allBooks.length);
    console.log("✅ Database seeding completed successfully!\n");

    await mongoose.connection.close();
    console.log("🔌 Database connection closed");
  } catch (error) {
    console.error("❌ Error seeding books:", error);
    process.exit(1);
  }
}

// Run the seed function
seedEngineeringBooks();

